- name: reload prometheus
  service: name=prometheus state=reloaded
- name: restart prometheus
  service: name=prometheus state=restarted
- name: restart prometheus_node_exporter
  service: name=prometheus_node_exporter state=restarted
- name: update apt
  command: apt-get update
- name: restart apache2
  service: name=apache2 state=restarted